#!/bin/sh

# Script for applying the Minecraft patch.
# Requires a repository with the Minecraft source code in the "mc" folder
# next to "src".
# Branches in that repo must be set up as follows:
# master: vanilla Minecraft code, as generated by the MCP.
# modded: modified Minecraft code, as generated by the apply-patch script.
# Before running this script, the "modded" branch must be created with
# "master" as its source.

cd ../mc
git checkout modded
git reset --hard master
git apply --ignore-space-change --ignore-whitespace ../patch/minecraft.patch

read -n1 -r -p "Press any key to continue..." key

