@echo off
rem # Script for applying the Minecraft patch.
rem # Requires a repository with the Minecraft source code in the "mc" folder
rem # next to "src".
rem # Branches in that repo must be set up as follows:
rem # master: vanilla Minecraft code, as generated by the MCP.
rem # modded: modified Minecraft code, as generated by the apply-patch script.
rem # Before running this script, the "modded" branch must be created with
rem # "master" as its source.

cd ..\mc
git checkout modded
git reset --hard master
git apply --ignore-space-change --ignore-whitespace ..\patch\minecraft.patch
rem pause
