#!/bin/sh

# Script for updating the Minecraft patch.
# Requires a repository with the Minecraft source code in the "mc" folder
# next to "src".
# Branches in that repo must be set up as follows:
# master: vanilla Minecraft code, as generated by the MCP.
# modded: modified Minecraft code, as generated by the apply-patch script.

cd ../mc
git checkout master
git checkout -b tmp
git merge --squash modded
git commit -a -m "mod"
git format-patch master --ignore-space-change
git checkout modded
git branch -D tmp
mv 0001-mod.patch ../patch/minecraft.patch

read -n1 -r -p "Press any key to continue..." key

